# Generated by Django 5.2.4 on 2025-07-18 02:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_decease_date_pet_homage_message_pet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('exam_type', models.CharField(max_length=100, verbose_name='Tipo de exame')),
                ('exam_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do exame')),
                ('vet_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do veterinário')),
                ('clinic_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da clínica')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('exam_file', models.FileField(blank=True, null=True, upload_to='exam_files/', verbose_name='Arquivo do exame')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do resultado')),
                ('value', models.CharField(max_length=200, verbose_name='Valor encontrado')),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Faixa de referência')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações do Resultado')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pets.exam')),
            ],
            options={
                'verbose_name': 'Resultado do Exame',
                'verbose_name_plural': 'Resultados do Exame',
                'unique_together': {('exam', 'name')},
            },
        ),
    ]
